### ISSUE TITLE
Exception in Native static constructor when PublishSingleFile

### ISSUE THREAD

**Issue by zgabi** [goldenbull/ManagedXZ#9]
Unhandled exception. System.TypeInitializationException: The type initializer for 'ManagedXZ.Native' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at ManagedXZ.Native..cctor()
   --- End of inner exception stack trace ---
   at ManagedXZ.XZDecompressStream.Init()
   at ManagedXZ.XZDecompressStream..ctor(Stream stream)
   at AisStreamer.Program.Main(String[] args)

Problem occurs when PublishSingleFile is true (.net core 3+). In this case the executing assembly's location is empty.

Would you accept a PR for fixing this and also fixing my other issue (#8)?

**Comment by zgabi** [comment]
Project is dead, created a fork which contains this fix.
